name: teste to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Listando nodes e pods
        run: |
          echo "$KUBECONFIG_K3S" > kubeconfig
          export KUBECONFIG=kubeconfig       
          kubectl get nodes

