name: List Kubernetes Nodes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  list-nodes:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Kubernetes CLI (kubectl)
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.24.0'

    - name: Set up Kubernetes config
      env:
        KUBECONFIG_K3S: ${{ secrets.KUBECONFIG_K3S }}
      run: echo "${KUBECONFIG_K3S}" > ~/.kube/config

    - name: List Kubernetes Nodes
      run: kubectl get nodes
