name: Uso de Variáveis no Repositório

on: workflow_dispatch  # Execução manual

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Definir variável de ambiente
        env:
          AMBIENTE: ${{ vars.AMBIENTE }}
        run: echo $AMBIENTE
