name: Uso de Variáveis no Repositório

on: workflow_dispatch  # Execução manual

jobs:
  example:
    runs-on: ubuntu-latest
    env: 
      AMBIENTE: ${{ vars.AMBIENTE }}    
    steps:
      - name: Exibir variável
        run: echo "O ambiente de execução é: $AMBIENTE"
